# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

asset_path: /home/cyqian/IsaacLab/scripts/environments/teleoperation/sharpa_duo/assets/robots/yam_ultra/right_yam.urdf
usd_dir: /home/cyqian/IsaacLab/scripts/environments/teleoperation/sharpa_duo/assets/robots/yam_ultra/right_yam
usd_file_name: right_yam/right_yam.usda
force_usd_conversion: true
make_instanceable: true
fix_base: true
root_link_name: null
link_density: 0.0
merge_fixed_joints: false
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: position
  gains:
    stiffness: 400.0
    damping: 80.0
collision_from_visuals: true
collision_type: Convex Decomposition
self_collision: false
replace_cylinders_with_capsules: false
merge_mesh: false
ros_package_paths: []
robot_type: Default
run_asset_transformer: true
run_multi_physics_conversion: true
debug_mode: false
##
# Generated by UrdfConverter on 2026-08-31 at 15:32:58.
##
